// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PolicyApiLibrary.DbModels
{
    [Table("PolicyUserType")]
    public partial class PolicyUserType
    {
        [Key]
        public int PolicyId { get; set; }
        [Key]
        public int UserTypeId { get; set; }

        [ForeignKey(nameof(PolicyId))]
        [InverseProperty("PolicyUserTypes")]
        public virtual Policy Policy { get; set; }
        [ForeignKey(nameof(UserTypeId))]
        [InverseProperty("PolicyUserTypes")]
        public virtual UserType UserType { get; set; }
    }
}