// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PolicyApiLibrary.DbModels
{
    [Table("Policy")]
    [Index(nameof(PolicyId), Name = "IX_Policy", IsUnique = true)]
    [Index(nameof(PolicyName), Name = "IX_Policy_1", IsUnique = true)]
    public partial class Policy
    {
        public Policy()
        {
            PolicyUserTypes = new HashSet<PolicyUserType>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string PolicyId { get; set; }
        [Required]
        [StringLength(100)]
        public string PolicyName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        public int DurationInYear { get; set; }
        [Required]
        [StringLength(100)]
        public string ComapnyName { get; set; }
        [Column(TypeName = "money")]
        public decimal InitialDeposit { get; set; }
        [Required]
        [StringLength(10)]
        public string PolicyTypeId { get; set; }
        public int TermsPerYear { get; set; }
        [Column(TypeName = "money")]
        public decimal TermAmount { get; set; }
        public double Interest { get; set; }

        [ForeignKey(nameof(PolicyTypeId))]
        [InverseProperty("Policies")]
        public virtual PolicyType PolicyType { get; set; }
        [InverseProperty(nameof(PolicyUserType.Policy))]
        public virtual ICollection<PolicyUserType> PolicyUserTypes { get; set; }
    }
}