// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PolicyApiLibrary.DbModels
{
    [Table("PolicyType")]
    public partial class PolicyType
    {
        public PolicyType()
        {
            Policies = new HashSet<Policy>();
        }

        [Key]
        [StringLength(10)]
        public string Id { get; set; }
        [Required]
        [StringLength(50)]
        public string TypeName { get; set; }

        [InverseProperty(nameof(Policy.PolicyType))]
        public virtual ICollection<Policy> Policies { get; set; }
    }
}