// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PolicyApiLibrary.DbModels
{
    [Table("UserType")]
    public partial class UserType
    {
        public UserType()
        {
            PolicyUserTypes = new HashSet<PolicyUserType>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string TypeName { get; set; }
        [Required]
        [StringLength(50)]
        public string IncomePerYear { get; set; }

        [InverseProperty(nameof(PolicyUserType.UserType))]
        public virtual ICollection<PolicyUserType> PolicyUserTypes { get; set; }
    }
}